# Generated by Django 3.2.13 on 2022-04-28 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date of last modified')),
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=40, prefix='', unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='article title')),
                ('description', models.TextField(verbose_name='description')),
                ('truncated_description', models.TextField(blank=True, null=True, verbose_name='truncated description')),
                ('link', models.URLField(max_length=2048, unique=True, verbose_name='article link')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('date_published', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_published'],
                'get_latest_by': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date of last modified')),
                ('feed_url', models.URLField(max_length=255, unique=True, verbose_name='feed URL')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('site_url', models.URLField(blank=True, null=True, verbose_name='site URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('frequency', models.IntegerField(default=10, verbose_name='frequency')),
                ('date_last_fetch', models.DateTimeField(auto_now=True, verbose_name='date of last fetch')),
            ],
            options={
                'verbose_name': 'Feed',
                'verbose_name_plural': 'Feeds',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date of last modified')),
                ('site_url', models.URLField(max_length=50, unique=True, verbose_name='source site url')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='logo url')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date of last modified')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date of last modified')),
                ('is_saved', models.BooleanField(default=False, verbose_name='is saved')),
                ('is_read_later', models.BooleanField(default=False, verbose_name='read later')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date of last modified')),
                ('name', models.CharField(max_length=50, verbose_name='folder name')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date of last modified')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.feed')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'feed')},
            },
        ),
        migrations.AddField(
            model_name='feed',
            name='folder',
            field=models.ManyToManyField(blank=True, related_name='feeds', through='news.FeedSubscription', to='news.Folder'),
        ),
        migrations.AddField(
            model_name='feed',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.source'),
        ),
        migrations.AddField(
            model_name='feed',
            name='topics',
            field=models.ManyToManyField(blank=True, to='news.Topic'),
        ),
        migrations.AddField(
            model_name='feed',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='feeds', through='news.FeedSubscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.feed'),
        ),
        migrations.AddField(
            model_name='article',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='articles', through='news.UserArticle', to=settings.AUTH_USER_MODEL),
        ),
    ]
