# Generated by Django 3.2.13 on 2022-04-15 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=255, verbose_name='article title')),
                ('description', models.TextField(verbose_name='description')),
                ('truncated_description', models.TextField(blank=True, null=True, verbose_name='truncated description')),
                ('link', models.URLField(max_length=2048, unique=True, verbose_name='article link')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('date_published', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_url', models.URLField(max_length=255, unique=True, verbose_name='feed URL')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('site_url', models.URLField(blank=True, null=True, verbose_name='site URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('date_last_fetch', models.DateTimeField(auto_now=True, verbose_name='date of last fetch')),
                ('frequency', models.IntegerField(default=10, verbose_name='frequency')),
            ],
            options={
                'verbose_name': 'Feed',
                'verbose_name_plural': 'Feeds',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField(max_length=50, unique=True, verbose_name='source name')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='logo url')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ReadLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='folder name')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('feeds', models.ManyToManyField(blank=True, to='news.Feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='news.source'),
        ),
        migrations.AddField(
            model_name='feed',
            name='topics',
            field=models.ManyToManyField(blank=True, to='news.Topic'),
        ),
        migrations.AddField(
            model_name='article',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.feed'),
        ),
        migrations.AddField(
            model_name='article',
            name='read_later',
            field=models.ManyToManyField(blank=True, through='news.ReadLater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(blank=True, to='news.Topic'),
        ),
    ]
