# Generated by Django 3.2.13 on 2022-04-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_feedsubscription_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='slug',
            field=models.SlugField(blank=True, default='no-slug', max_length=255),
        ),
        migrations.AddField(
            model_name='folder',
            name='slug',
            field=models.SlugField(blank=True, default='no-slug', max_length=60),
        ),
    ]
