# Generated by Django 3.2.13 on 2022-04-30 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_auto_20220429_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='folder',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'user')},
        ),
    ]
