# Generated by Django 3.2.13 on 2022-05-01 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220430_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='folder',
            new_name='folders',
        ),
    ]
