# Generated by Django 3.2.13 on 2022-05-27 03:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0007_auto_20220506_0252'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userarticle',
            unique_together={('user', 'article')},
        ),
    ]
